#!/usr/local/bin/node

const express = require('express');
const app = express();

const bodyParser = require('body-parser');
app.use(bodyParser.urlencoded({ extended: false }));


app.listen('3333', () => {
	console.log('listening on port 3333')
});

app.get('/', (req, res) => {
	res.end('ok');
});

app.post('/', (req, res) => {
	res.json({
		content: req.body,
		success: true
	})
});

